### ISSUE TITLE
Ignition handling of various cloud providers

### ISSUE THREAD

**Issue by jlebon** [openshift/os#101]
Right now, we have some magic in [bootengine](https://github.com/dustymabe/bootengine/) for detecting AWS based on Xen and OpenStack based on `dmidecode` output, though this is clearly not ideal. IIUC, CL had different OEM packages for each cloud that drops in a small grub cfg script which is used at runtime to build the kernel cmdline, e.g. https://github.com/coreos/coreos-overlay/blob/master/coreos-base/oem-gce/files/grub.cfg. 

One idea is to have a small libguestfs script that does something similar for each cloud-specific image we provide before uploading them?

**Comment by cgwalters** [comment]
> One idea is to have a small libguestfs script that does something similar for each cloud-specific image we provide before uploading them?

That doesn't seem too bad for handling the AWS/Azure/GCE cases + OpenStack, but gets uglier the farther we take it; the more that literally the same disk image works for both AWS and OpenStack and VMWare, the better.

Eh.  I'm fine with that approach since others seemed negative on the dynamic detection but...it feels to me we can make something like the `dmidecode` fairly reliable in some cases - if it breaks we're going to notice.

**Comment by bgilbert** [comment]
If platform detection breaks, it may break only on certain instance types or with certain platform configurations, which may take a while to notice.

**Comment by cgwalters** [comment]
That's a valid concern, in fact the change Dusty made to do "xen == ec2" definitely breaks with the new KVM instances, however:

```
[root@ip-172-18-6-44 ~]# systemd-detect-virt 
kvm
[root@ip-172-18-6-44 ~]# dmidecode |grep 'Amazon EC2'
        Vendor: Amazon EC2
        Manufacturer: Amazon EC2
        Manufacturer: Amazon EC2
        Manufacturer: Amazon EC2
        Asset Tag: Amazon EC2
```

But eh...I'm fine switching to postprocessing too.

**Comment by jlebon** [comment]
My issue with using output from `dmidecode` is that it's implicit. It's not really a stable "API" we can bank on. I see that e.g. AWS docs themselves promote using `/sys/hypervisor/uuid` or `dmidecode` (but only for HVM instances): https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html, and even then, there are caveats: https://serverfault.com/a/700771. From a quick search, I couldn't find such firm declarations from the other clouds.

The only true API I can think of we have at our disposal is how metadata is fetched. So we could go the cloud-init route and teach ignition to try all those different ways. Not sure how we feel about that... We could also do a combination of the two; post-process for the big ones, and a generic image where ignition just auto-detects for everything else.

**Comment by cgwalters** [comment]
Strawman PR in https://github.com/openshift/os/pull/106

**Comment by dustymabe** [comment]
while i really would like to add "detection" logic (so if people somehow grabbed our cloud image and uploaded it themselves for whatever reason) I understand wanting to be explicit. What I'd like to prevent is building 6 different images and then uploading them. The guestfish workaround in #106 seems reasonable for now since it only makes the change right before we upload the image.

**Comment by ashcrow** [comment]
I agree. If possible it would be ideal to upload one image converted to whatever cloud format is required.

**Comment by cgwalters** [comment]
This is implemented now, I confirmed that:

```
[root@ip-172-18-4-84 ~]# grep -o coreos.oem.id='[a-z0-9]*' /proc/cmdline 
coreos.oem.id=ec2
[root@ip-172-18-4-84 ~]# systemd-detect-virt 
kvm
```

**Comment by jlebon** [comment]
Confirmed working in OpenStack as well! I was able to pass an ignition config through `openstack server create --user-data` (this didn't work previously because ignition didn't know it was running on OpenStack).

**Comment by jlebon** [comment]
https://github.com/dustymabe/bootengine/pull/10
