### ISSUE TITLE
Update version to be inline with 

### ISSUE THREAD

**Issue by ashcrow** [openshift/os#360]
Per https://github.com/openshift/os/issues/259, our version in RHCOS should be updated to follow `$OCPMAJORMINORPATH.$RHELMAJOR.$DATE+$BUILD`

Examples:
- `400.7.20180901+001`
- `400.8.20180905+005`
- `410.8.20180915+001`

**Comment by ashcrow** [comment]
Looking at the pipeline output in v2 this looks like it's done. Does that sound accurate @cgwalters?

**Comment by ashcrow** [comment]
Never mind, verified this morning this is NOT done.

**Comment by ashcrow** [comment]
It looks like the treefile syntax [doesn't support increment builds without the dot](https://github.com/projectatomic/rpm-ostree/blob/master/docs/manual/treefile.md). Any objection to replacing the end `+` with a `.` like $OCPMAJORMINORPATH.$RHELMAJOR.$DATE.$BUILD?

EG: 

```diff
-automatic_version_prefix: "47"
+automatic_version_prefix: "400.7.<date:%Y%m%d>"
```

Outputing: `400.7.20180116.1`

**Comment by rfairley** [comment]
Sorry should have checked back on this before - the recent addition to add the `<date:` tag in (https://github.com/projectatomic/rpm-ostree/pull/1721) was constrained in maintaining the "always appending an increment" behaviour. Right now - this increment is always appended as `.x` with x being the build number.

We could add in options to allow a plus sign to be appended (e.g. `<increment_separator:+>` somewhere in the prefix would mean `+x` gets appended instead of `.x`). To have zero padding, a `<zero_padding:3>` tag could be supported to pad the appended version number with zeroes to 3 digits (e.g. `00x`).

If these options would be good to have, the logic for them would fit in cleanly along with the current `<date:` tag.

/cc @jlebon

**Comment by ashcrow** [comment]
@rfairley thanks! Personally, I don't think it's worth updating `rpm-ostree`, getting new builds available for use, and then referencing them just for the `+` -> `.` but it is a fair conversation to have :-)

**Comment by jlebon** [comment]
Are we planning to have more than 99 builds per day? That sounds unlikely. :)

Otherwise, `.` vs `+` sounds kinda bikesheddy. :house: :paintbrush: I personally prefer dots, but if we feel strongly about it, sure, we could add a knob to change the separator.

**Comment by rfairley** [comment]
Alright - SGTM to leave it at dots :) . Just wanted to make sure we weren't limited in case there was a strong preference for `+`.

**Comment by ashcrow** [comment]
OK perfect. I'll pick this back up with `.`.

**Comment by miabbott** [comment]
Super late to the conversation here, but just wanted to ask this:

> one of the reasons we went with + I think was to try to comply with semver, but I don't think it really matters that much.

My memory might be failing, but I thought we weren't trying to comply to semver?

**Comment by dustymabe** [comment]
from #259 i thought we were trying to keep our version string to comply with semver, but we weren't necessarily making the same guarantees that semver does regarding API etc...

At this point let's go with `.` as suggested above.

**Comment by ashcrow** [comment]
PR submitted

**Comment by ashcrow** [comment]
This has been implemented in the v3 pipeline and is currently pumping out images.
