### ISSUE TITLE
extend to more AWS regions

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#371]
Today we only upload to a few regions; I'm wary of the costs of uploading *every* build to all regions.

One path would be for the installer folks, when they [pin a release](https://github.com/openshift/installer/pull/757) to ping us and we'll run a "buildextend" style invocation that uploads the image to more targeted regions.

Another thing we should probably do is pick at least one region in Europe and one in Asia for all development builds too.

**Comment by wking** [comment]
Cross-ref https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!topic/openshift-4-dev-preview/6OLJ1J-UvwU

**Comment by ashcrow** [comment]
At this point I believe we are now uploading to multiple regions.

**Comment by ashcrow** [comment]
Closing this issue. Feel free to re-open if I'm mistaken.

**Comment by wking** [comment]
There are still some regions where we don't upload AMIs (see commented-out regions [here][1]).  But I'm fine closing this issue and re-opening region-specific issues if/when we get further complaints.  I think the real solution to this is going to be cross-region copy-and-encrypt, with Red-Hat-published AMIs living in a single region.  We do that for control-plane machines since openshift/installer#1296, but still need machine-API-provider work before we can do it for compute machines.

[1]: https://github.com/openshift/installer/commit/4e08718dd55ffb3f130ed62c2aa0090a523759f3#diff-b2d0a195ba9ad18dacb40f24d7e3316cR15
