### ISSUE TITLE
remove null LUKS container, transition to Ignition LUKS on upgrade

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#426]
Some discussion of this here https://hackmd.io/jBhJUEIqSdOfmnZR-aI0_g?edit

**Comment by arithx** [comment]
My general approach is: remove the [`crypt_rootfs` section from COSA](https://github.com/coreos/coreos-assembler/blob/master/src/create_disk.sh#L158-L199), stop setting the [`rhcos.luks` karg](https://github.com/openshift/os/blob/master/image.yaml#L9), rip out all everything but the unlocking bits from [`coreos-cryptfs`](https://github.com/openshift/os/blob/master/overlay.d/05rhcos/usr/libexec/coreos-cryptfs), add a bash script (see more below) that runs in the real root every boot for the duration of 4.7.

The bash script running in the real root is there to do two main things: changing the old `rhcos.luks` kargs -> `rd.luks` (which is what the new Ignition LUKS uses) & fixing the partition table in the case of null_cipher (unencrypted) root devices. For the second case right now if we have a non-encrypted root device we have the root device inside a `null_cipher-esb` volume. To avoid performance hits we create a [dm-linear mapping of the partition minus the LUKS header](https://github.com/openshift/os/blob/master/overlay.d/05rhcos/usr/libexec/coreos-cryptfs#L117-L136), the bash script is just doing that in a permanent way (modifying the partition table changing the starting offset of the partition to omit the LUKS header instead of creating the dm-linear mapping on every boot).

The main idea behind this approach is optimized around
1) remove the legacy ways of touching the root filesystem (Ignition should be handling this in all cases now)
1) not needing an update barrier; for the entire duration of 4.7 we can still detect & unlock previous versions root filesystems, we are just fixing them after we detect them so that we won't need to carry the `coreos-cryptfs` openers starting in 4.8
