### ISSUE TITLE
RHCOS 4.11 + RHEL 8.6 x86: Failed to insert 'ipmi_si': No such device

### ISSUE THREAD

**Issue by jschintag** [openshift/os#749]
When runnning RHCOS 4.11 based on RHEL 8.6 on x86, the `systemd-modules-load.service` fails to load the `ipmi_si` module.
```
# systemctl status systemd-modules-load
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static; vendor preset: disabled)
   Active: active (exited) since Thu 2022-03-17 12:01:09 UTC; 8min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 928 ExecStart=/usr/lib/systemd/systemd-modules-load (code=exited, status=0/SUCCESS)
 Main PID: 928 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 5555)
   Memory: 0B
   CGroup: /system.slice/systemd-modules-load.service

Mar 17 12:01:09 localhost systemd-modules-load[928]: Module 'msr' is builtin
Mar 17 12:01:09 localhost systemd[1]: Started Load Kernel Modules.

# dmesg | grep ipmi
[    8.582521] ipmi device interface
[    8.633522] ipmi_si: IPMI System Interface driver
[    8.640952] ipmi_si: Unable to find any System Interface(s)
[    8.659581] systemd-modules-load[384]: Failed to insert 'ipmi_si': No such device
```
Relate bug https://bugzilla.redhat.com/show_bug.cgi?id=2037294

**Comment by HuijingHei** [comment]
Check on 4.11 (based on rhel8.5) and 4.10 (based on rhel8.4), no such issue. And no ipmi related modules found

**Comment by jschintag** [comment]
Looking at the BZ and comparing it to s390x, i think we have to different problems here depending on platform:
x86:
- missing device for `ipmi_si` kernel module
- potentially fixed in the BZ
s390x:
- missing `ipmi` modules (not installed by rpm)
```
[core@cosa-devsh char]$ rpm -ql kernel-core | grep ipmi
[core@cosa-devsh char]$ rpm -ql kernel-modules | grep ipmi
```

**Comment by HuijingHei** [comment]
Upgrade to fwupd-1.7.1-1.el8.x86_64, result is the same as https://bugzilla.redhat.com/show_bug.cgi?id=2037294#c8
```
# systemctl status systemd-modules-load
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static; vendor preset: disabled)
   Active: active (exited) since Thu 2022-03-17 12:01:09 UTC; 8min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 928 ExecStart=/usr/lib/systemd/systemd-modules-load (code=exited, status=0/SUCCESS)
 Main PID: 928 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 5555)
   Memory: 0B
   CGroup: /system.slice/systemd-modules-load.service

Mar 17 12:01:09 localhost systemd-modules-load[928]: Module 'msr' is builtin
Mar 17 12:01:09 localhost systemd[1]: Started Load Kernel Modules.

# dmesg | grep ipmi
[    8.582521] ipmi device interface
[    8.633522] ipmi_si: IPMI System Interface driver
[    8.640952] ipmi_si: Unable to find any System Interface(s)
[    8.659581] systemd-modules-load[384]: Failed to insert 'ipmi_si': No such device
```

**Comment by cgwalters** [comment]
>  i came up with would be a simple test that checks that there are no failed services after boot.

We have code for that, see https://github.com/coreos/coreos-assembler/blob/af765bd8a6a0ae7b54118af4a9227db6d58c21ea/mantle/platform/platform.go#L407
I think we should figure out why that test wasn't firing.

Short term though, I think we should pile onto the bugzilla instead of adding a lot more information here, because the relevant maintainer is watching the BZ, but is not watching chat here (as far as I know).

**Comment by jschintag** [comment]
> We have code for that, see https://github.com/coreos/coreos-assembler/blob/af765bd8a6a0ae7b54118af4a9227db6d58c21ea/mantle/platform/platform.go#L407 I think we should figure out why that test wasn't firing.

I mean you get the message when you start a console in rhcos, but i meant more of a kola test, since i think our testsuite should detect this as well.

> 
> Short term though, I think we should pile onto the bugzilla instead of adding a lot more information here, because the relevant maintainer is watching the BZ, but is not watching chat here (as far as I know).

Agree for x86, but s390x is a different issue (same failed service, different reason). My Proposal would be to use this issue for s390x and track x86 in the BZ?

**Comment by miabbott** [comment]
> We have code for that, see https://github.com/coreos/coreos-assembler/blob/af765bd8a6a0ae7b54118af4a9227db6d58c21ea/mantle/platform/platform.go#L407
> I think we should figure out why that test wasn't firing.

I think there are two things causing this:

1. the `systemd-modules-load.service` isn't reporting a failed state when it failed to load `ipmi_si`.  See the [comment from Huijing above](https://github.com/openshift/os/issues/749#issuecomment-1070855518) where the module failed to load, but the service is reporting `active (exited)`

2. the code checking for `systemd` unit failures is giving false positives on RHCOS

https://github.com/coreos/coreos-assembler/blob/d9f3971f0d195737e9d3e22cfc733f3aa932577b/mantle/platform/platform.go#L481

`busctl` doesn't have the `--json=short` option on RHCOS.  That was added back in [Oct 2018](https://github.com/systemd/systemd/commit/9cebb234b187b468a1d7165e4505403386b45226) and was first included in v240. But sadly, RHCOS is still stuck on v239.

So when you call `busctl --json=short ...` on RHCOS, it fails. But since the output is piped to `jq`, the return code is masked because the filter used with `jq` is valid and just doesn't match anything:

```bash
[core@cosa-devsh ~]$ busctl --json=short call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager ListUnitsFiltered as 2 state failed
busctl: unrecognized option '--json=short'
[core@cosa-devsh ~]$ echo $?
1
[core@cosa-devsh ~]$ busctl --json=short call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager ListUnitsFiltered as 2 state failed | jq -r '.data[][][0]'
busctl: unrecognized option '--json=short'
[core@cosa-devsh ~]$ echo $?
0
```

We can fix the `mantle` code for RHCOS, but we'll need to wait for a fix for  https://bugzilla.redhat.com/show_bug.cgi?id=2037294 for the `ipmi_si` problem/

**Comment by cgwalters** [comment]
(everywhere above, S/RHCOS/RHEL8/ - just a general reminder because RHEL9 is coming...)

**Comment by HuijingHei** [comment]
Correct the above result:
Both upgrade to `fwupd-1.7.4-1.el8.x86_64`, test on rhcos 4.11(with rhel8.6), compared with origin rhel8.6 VM. 
The difference is: rhcos has log `systemd-modules-load[385]: Failed to insert 'ipmi_si': No such device`, also add comment in https://bugzilla.redhat.com/show_bug.cgi?id=2037294#c22

**Comment by jschintag** [comment]
@cgwalters @HuijingHei I think the fact that i initially reported the issue for s390x, when we have different issues on x86 and s390x is confusing us (at the least it is causing some misscommunication).
Therefore i updated the description of this issue and created a separate one for s390x (#752).

**Comment by cgwalters** [comment]
We have a fixed fwupd I believe
