### ISSUE TITLE
ostree compose not properly detected "changes"

### ISSUE THREAD

**Issue by dustymabe** [openshift/os#85]
I have identified two compose runs that obviously have different content in them that is reporting "no changes": 

The [jenkins pipeline view](https://continuous-infra-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/rhcos/job/coreos-rhcos-treecompose/) shows [1168](https://continuous-infra-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/rhcos/job/coreos-rhcos-treecompose/1168/console) building with `ignition-0.23.0-0.7.el7.x86_64 (dustymabe-ignition)` and [1169](https://continuous-infra-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/rhcos/job/coreos-rhcos-treecompose/1169/console) buildilng with `ignition-0.23.0-0.8.el7.x86_64` but 1169 reports at the bottom: `No apparent changes since previous commit`

**Comment by ashcrow** [comment]
Looks like it is still finding no chances.

**Note**: This issue blocks work which is blocking further work.

**Comment by jlebon** [comment]
I don't think there's an issue here. The pipeline has a "Check for Changes" step and a "Compose Tree" step. What happened in build 1168 is that during the "Check for Changes" step, it saw `ignition-0.23.0-0.7.el7.x86_64`, but during the actual compose step, it pulled in `ignition-0.23.0-0.8.el8.x86_64`. So it just looks confusing because at first glance it seems like the older build was pulled in. But scrolling down further, you should see the final list of packages that were actually composed.

**Comment by dustymabe** [comment]
> (So essentially, a perfectly timed race between the COPR build and the treecompose job).

roger. that wasn't confusing at all :)
